# Generated by Django 2.2.7 on 2019-11-15 13:26

from django.db import migrations, models
import django.db.models.deletion
import itboard.models


class Migration(migrations.Migration):
    dependencies = [
        ('itboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(upload_to=itboard.models.image_file)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images',
                                           to='itboard.Post')),
            ],
            options={
                'db_table': 'sc_image',
            },
        ),
    ]
